In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('/content/Customer-Churn-Records.csv')

In [3]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Complain,Satisfaction Score,Card Type,Point Earned
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1,2,DIAMOND,464
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,1,3,DIAMOND,456
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,1,3,DIAMOND,377
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0,5,GOLD,350
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0,5,GOLD,425

# Data Exploring

In [4]:
data.sample()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Complain,Satisfaction Score,Card Type,Point Earned
47,48,15771573,Okagbue,637,Germany,Female,39,9,137843.8,1,1,1,117622.8,1,1,1,SILVER,730

In [5]:
data.shape

(10000, 18)

In [6]:
data.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Complain,Satisfaction Score,Point Earned
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203800,0.204400,3.013800,606.515100
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402842,0.403283,1.405919,225.924839
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000,0.000000,1.000000,119.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000,0.000000,2.000000,410.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000,0.000000,3.000000,605.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000,0.000000,4.000000,801.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000,1.000000,5.000000,1000.000000

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   RowNumber           10000 non-null  int64
 1   CustomerId          10000 non-null  int64
 2   Surname             10000 non-null  object
 3   CreditScore         10000 non-null  int64
 4   Geography           10000 non-null  object
 5   Gender              10000 non-null  object
 6   Age                 10000 non-null  int64
 7   Tenure              10000 non-null  int64
 8   Balance             10000 non-null  float64
 9   NumOfProducts       10000 non-null  int64
 10  HasCrCard           10000 non-null  int64
 11  IsActiveMember      10000 non-null  int64
 12  EstimatedSalary     10000 non-null  float64
 13  Exited              10000 non-null  int64
 14  Complain            10000 non-null  int64
 15  Satisfaction Score  10000 non-null  int64
 16  Card Type           10000 non-null  object
 17  Point Earned        10000 non-null  int64
dtypes: float64(2), int64(12), object(4)
memory usage: 1.4+ MB

## we need to convert three categorical columms into numerical columns

###Geography, Gender, Card Type

## Dropping the Irrelevant columns

In [8]:
data = data.drop(columns=['Surname', 'RowNumber', 'CustomerId'], axis=1)

In [9]:
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Complain,Satisfaction Score,Card Type,Point Earned
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1,2,DIAMOND,464
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,1,3,DIAMOND,456
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,1,3,DIAMOND,377
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0,5,GOLD,350
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0,5,GOLD,425

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CreditScore         10000 non-null  int64
 1   Geography           10000 non-null  object
 2   Gender              10000 non-null  object
 3   Age                 10000 non-null  int64
 4   Tenure              10000 non-null  int64
 5   Balance             10000 non-null  float64
 6   NumOfProducts       10000 non-null  int64
 7   HasCrCard           10000 non-null  int64
 8   IsActiveMember      10000 non-null  int64
 9   EstimatedSalary     10000 non-null  float64
 10  Exited              10000 non-null  int64
 11  Complain            10000 non-null  int64
 12  Satisfaction Score  10000 non-null  int64
 13  Card Type           10000 non-null  object
 14  Point Earned        10000 non-null  int64
dtypes: float64(2), int64(10), object(3)
memory usage: 1.1+ MB

In [11]:
data['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [12]:
data['Card Type'].unique()

array(['DIAMOND', 'GOLD', 'SILVER', 'PLATINUM'], dtype=object)

In [13]:
data['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [14]:
data.isnull().sum()

CreditScore           0
Geography             0
Gender                0
Age                   0
Tenure                0
Balance               0
NumOfProducts         0
HasCrCard             0
IsActiveMember        0
EstimatedSalary       0
Exited                0
Complain              0
Satisfaction Score    0
Card Type             0
Point Earned          0
dtype: int64

# Data is Imbalanced we will perfrom SMOTE technique after tranaformation

In [15]:
data['Exited'].value_counts()

Exited
0    7962
1    2038
Name: count, dtype: int64

# Define Input and Output data

In [16]:
X = data.drop(columns=['Exited'])
y = data['Exited']

In [17]:
X.shape

(10000, 14)

In [18]:
y.shape

(10000,)

In [19]:
X.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Complain,Satisfaction Score,Card Type,Point Earned
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1,2,DIAMOND,464
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,1,3,DIAMOND,456
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,3,DIAMOND,377
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0,5,GOLD,350
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,5,GOLD,425

# Converting Categorical columns into numerical using OneHotEncoding

In [20]:
cat_cols= ['Geography', 'Gender', 'Card Type']
num_cols = ['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Complain', 'Satisfaction Score', 'Point Earned']

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)

In [22]:
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

preprocess = ColumnTransformer(transformers=[
    ('num', StandardScaler(), num_cols),
    ('cat', OneHotEncoder(drop='first', handle_unknown='ignore'), cat_cols)
])

In [23]:
X_scaled = preprocess.fit_transform(X_train)
X_test_scaled = preprocess.transform(X_test)

In [24]:
X_scaled.shape

(8000, 17)

In [25]:
X_test_scaled.shape

(2000, 17)

In [26]:
print(X_scaled)

[[ 1.03360928  0.00825566  0.34955973 ...  0.          1.
   0.        ]
 [ 0.78536369 -0.46826153 -0.69053865 ...  0.          1.
   0.        ]
 [-0.64204841  2.39084161 -0.69053865 ...  0.          0.
   1.        ]
 ...
 [-0.69376624 -0.75417184 -0.34383919 ...  0.          0.
   0.        ]
 [ 0.29921609 -0.27765465  0.34955973 ...  0.          1.
   0.        ]
 [-1.66606145  1.24720035 -1.38393756 ...  1.          0.
   0.        ]]

# Balanced the data Using SMOTE only on training data

In [27]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_train1, y_train1 = smote.fit_resample(X_scaled, y_train)

In [28]:
X_train1.shape

(12734, 17)

In [29]:
y_train1.value_counts()

Exited
0    6367
1    6367
Name: count, dtype: int64

In [30]:
X_train.shape, y_train.shape

((8000, 14), (8000,))

# Now everything is done, next step is to do model training

##1. Logistic Regression

In [31]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

lr.fit(X_train1, y_train1)

LogisticRegression()

### Evaluation of 1st model

In [32]:
y_pred1 = lr.predict(X_test_scaled)

In [33]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print(accuracy_score(y_test, y_pred1))
print(confusion_matrix(y_test, y_pred1))
print(classification_report(y_test, y_pred1))

0.9995
[[1594    1]
 [   0  405]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1595
           1       1.00      1.00      1.00       405

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000

## 2. Model

In [34]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()

dt.fit(X_train1, y_train1)

DecisionTreeClassifier()

In [35]:
y_pred2 = dt.predict(X_test_scaled)

In [36]:
print(accuracy_score(y_test, y_pred2))
print(confusion_matrix(y_test, y_pred2))

0.9985
[[1593    2]
 [   1  404]]

In [37]:
print(classification_report(y_test, y_pred2))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1595
           1       1.00      1.00      1.00       405

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000

## 3. SVM

In [38]:
from sklearn.svm import SVC

svm = SVC()

svm.fit(X_train1, y_train1)

SVC()

In [39]:
y_pred3 = svm.predict(X_test_scaled)

In [40]:
print(accuracy_score(y_test, y_pred3))
print(confusion_matrix(y_test, y_pred3))

0.9995
[[1594    1]
 [   0  405]]

In [41]:
print(classification_report(y_test, y_pred3))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1595
           1       1.00      1.00      1.00       405

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000

##4. KNN

In [43]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()

knn.fit(X_train1, y_train1)

KNeighborsClassifier()

In [44]:
y_pred4 = knn.predict(X_test_scaled)

In [45]:
print(accuracy_score(y_test, y_pred4))
print(confusion_matrix(y_test, y_pred4))

0.9995
[[1594    1]
 [   0  405]]

In [46]:
print(classification_report(y_test, y_pred4))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1595
           1       1.00      1.00      1.00       405

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000

##5. Random Forest

In [47]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100, random_state=42)

rf.fit(X_train1, y_train1)

RandomForestClassifier(random_state=42)

In [48]:
y_pred5 = rf.predict(X_test_scaled)

In [49]:
print(accuracy_score(y_test, y_pred5))
print(confusion_matrix(y_test, y_pred5))

0.9995
[[1594    1]
 [   0  405]]

##6. Gradient Boosting

In [50]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier()

gb.fit(X_train1, y_train1)

GradientBoostingClassifier()

In [51]:
y_pred6 = gb.predict(X_test_scaled)

In [52]:
print(accuracy_score(y_test, y_pred6))
print(confusion_matrix(y_test, y_pred6))

0.999
[[1593    2]
 [   0  405]]

In [53]:
print(classification_report(y_test, y_pred6))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1595
           1       1.00      1.00      1.00       405

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000

In [54]:
final_data = pd.DataFrame({'Models': ['LR', 'SVC', 'KNN','DT', 'RF', 'GBC'], 'ACC': [accuracy_score(y_test,y_pred1),
                                                                                    accuracy_score(y_test,y_pred2),
                                                                                    accuracy_score(y_test,y_pred3),
                                                                                    accuracy_score(y_test,y_pred4),
                                                                                    accuracy_score(y_test,y_pred5),
                                                                                    accuracy_score(y_test,y_pred6),]})

In [55]:
final_data

  Models     ACC
0     LR  0.9995
1    SVC  0.9985
2    KNN  0.9995
3     DT  0.9995
4     RF  0.9995
5    GBC  0.9990

# Creating Pipeline using Random Forest Model

In [56]:
model = RandomForestClassifier(n_estimators=1000)

In [60]:
from imblearn.pipeline import Pipeline

In [61]:
pipeline = Pipeline([
    ('preprocess', preprocess),
    ('smote', SMOTE(random_state=42)),
    ('model', model)
])

In [62]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['CreditScore', 'Age',
                                                   'Tenure', 'Balance',
                                                   'NumOfProducts', 'HasCrCard',
                                                   'IsActiveMember',
                                                   'EstimatedSalary',
                                                   'Complain',
                                                   'Satisfaction Score',
                                                   'Point Earned']),
                                                 ('cat',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'),
                                                  ['Geography', 'Gender',
                                                   'Card Type'])])),
                ('smote', SMOTE(random_state=42)),
                ('model', RandomForestClassifier(n_estimators=1000))])

In [63]:
y_predd = pipeline.predict(X_test)

#Evaluation

In [64]:
print('Accuracy :', accuracy_score(y_test, y_predd))

Accuracy : 0.9995

In [66]:
print('Confusion Matrix :\n', confusion_matrix(y_test, y_predd))

Confusion Matrix :
 [[1594    1]
 [   0  405]]

In [69]:
print('Classification Report : \n', classification_report(y_test, y_predd))

Classification Report :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      1595
           1       1.00      1.00      1.00       405

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000

In [68]:
from sklearn.metrics import precision_score, f1_score

In [70]:
print('Precision Score :' , precision_score(y_test, y_predd))

Precision Score : 0.9975369458128078

In [72]:
print('f1 Score :', f1_score(y_test, y_predd, average='weighted'))

f1 Score : 0.9995002298669247

#Exporting/Save the Model

In [73]:
import joblib

joblib.dump(pipeline, 'churn_pipeline.pkl')

['churn_pipeline.pkl']

In [74]:
from tkinter import *