In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('spam_data.csv')

In [3]:
df.head()

   label                                               text
0      1  ounce feather bowl hummingbird opec moment ala...
1      1  wulvob get your medircations online qnb ikud v...
2      0   computer connection from cnn com wednesday es...
3      1  university degree obtain a prosperous future m...
4      0  thanks for all your answers guys i know i shou...

In [4]:
df['label'].value_counts()

label
1    43910
0    39538
Name: count, dtype: int64

In [5]:
df.sample(10)

       label                                               text
19456      1  she had had many a hint from mr knightley and ...
44600      1  anxiety on these accounts hereafter you shall ...
44002      1  dear sirs aegis capital group llc aegis is a...
82265      0  steve bertrand wrote i have two scenarios here...
4644       1  massive rock - solid erections in 60 seconds o...
80641      1  i met me { disithis } { chickieigirlie } , she...
82080      1  these pills are just like regular cialis but t...
24627      1  suspended discs produced distinct wintab altta...
7009       0  el ad david amir wrote i'm slowly moving my st...
30495      0  accuweather escapenumber day forecast for beve...

# 1. Text Cleaning

In [6]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'\d+', '', text)        # remove numbers
    text = re.sub(r'[^\w\s]', '', text)    # remove punctuation
    text = re.sub(r'\s+', ' ', text)       # remove extra spaces
    return text

In [7]:
df['input'] = df['text'].apply(clean_text)

In [8]:
df.head()

,label,text,input
0,1,ounce feather bowl hummingbird opec moment ala...,ounce feather bowl hummingbird opec moment ala...
1,1,wulvob get your medircations online qnb ikud v...,wulvob get your medircations online qnb ikud v...
2,0,computer connection from cnn com wednesday es...,computer connection from cnn com wednesday es...
3,1,university degree obtain a prosperous future m...,university degree obtain a prosperous future m...
4,0,thanks for all your answers guys i know i shou...,thanks for all your answers guys i know i shou...

In [9]:
df.sample(10)

,label,text,input
51321,0,on thu jun escapenumber escapenumber at escape...,on thu jun escapenumber escapenumber at escape...
72080,1,dear sirs aegis capital group llc aegis is a...,dear sirs aegis capital group llc aegis is a s...
29457,0,escapenumber escapenumber escapenumber escape...,escapenumber escapenumber escapenumber escape...
3608,0,"please see announcement below .\npilar , linda...",please see announcement below pilar linda indi...
69145,0,escapenumberfxml version escapenumberd escape...,escapenumberfxml version escapenumberd escape...
65017,1,leader reading remained matter room and blue h...,leader reading remained matter room and blue h...
9465,0,rangalo wrote powersave u u is for suspend to ...,rangalo wrote powersave u u is for suspend to ...
64514,1,browse search order my esoft community back to...,browse search order my esoft community back to...
41346,0,"fernley ,\non january 25 , 1999 , i had breakf...",fernley on january i had breakfast in london w...
58168,1,looks coming hours call\nsuper cheaap software...,looks coming hours call super cheaap softwares...

In [10]:
df = df.drop('text', axis=1)

In [11]:
df.shape

(83448, 2)

In [12]:
df.head()

   label                                              input
0      1  ounce feather bowl hummingbird opec moment ala...
1      1  wulvob get your medircations online qnb ikud v...
2      0   computer connection from cnn com wednesday es...
3      1  university degree obtain a prosperous future m...
4      0  thanks for all your answers guys i know i shou...

# 2. Tokenization

In [13]:
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

df['tokens'] = df['input'].apply(word_tokenize)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

#3. Remove StopWords

In [14]:
from nltk.corpus import stopwords
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

df['tokens'] = df['tokens'].apply(
    lambda x: [word for word in x if word not in stop_words]
)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

#4. Stemming / Lemmatization

In [15]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

lemmatizer = WordNetLemmatizer()

df['tokens'] = df['tokens'].apply(
    lambda x: [lemmatizer.lemmatize(word) for word in x]
)

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

#5. Convert text to numbers

In [16]:
df.head()

,label,input,tokens
0,1,ounce feather bowl hummingbird opec moment ala...,"[ounce, feather, bowl, hummingbird, opec, mome..."
1,1,wulvob get your medircations online qnb ikud v...,"[wulvob, get, medircations, online, qnb, ikud,..."
2,0,computer connection from cnn com wednesday es...,"[computer, connection, cnn, com, wednesday, es..."
3,1,university degree obtain a prosperous future m...,"[university, degree, obtain, prosperous, futur..."
4,0,thanks for all your answers guys i know i shou...,"[thanks, answer, guy, know, checked, rsync, ma..."

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000)
X = tfidf.fit_transform(df['input'])

#6. Encode

In [18]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(df['label'])

In [19]:
y

array([1, 1, 0, ..., 1, 0, 1])

In [20]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 7726375 stored elements and shape (83448, 5000)>

In [21]:
df.head()

,label,input,tokens
0,1,ounce feather bowl hummingbird opec moment ala...,"[ounce, feather, bowl, hummingbird, opec, mome..."
1,1,wulvob get your medircations online qnb ikud v...,"[wulvob, get, medircations, online, qnb, ikud,..."
2,0,computer connection from cnn com wednesday es...,"[computer, connection, cnn, com, wednesday, es..."
3,1,university degree obtain a prosperous future m...,"[university, degree, obtain, prosperous, futur..."
4,0,thanks for all your answers guys i know i shou...,"[thanks, answer, guy, know, checked, rsync, ma..."

In [22]:
X.shape

(83448, 5000)

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)

In [25]:
X_train.shape

(66758, 5000)

In [26]:
X_test.shape

(16690, 5000)

# Model - 1. Naive Bayes

In [27]:
from sklearn.naive_bayes import MultinomialNB

In [28]:
nb = MultinomialNB()
nb.fit(X_train, y_train)

MultinomialNB()

In [29]:
y_pred = nb.predict(X_test)

In [30]:
from sklearn.metrics import accuracy_score, classification_report

In [31]:
accuracy_score(y_test, y_pred)

0.9626123427201917

In [32]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.96      0.97      0.96      7907
           1       0.97      0.96      0.96      8783

    accuracy                           0.96     16690
   macro avg       0.96      0.96      0.96     16690
weighted avg       0.96      0.96      0.96     16690

# Model - 2. Logistic Regression

In [33]:
from sklearn.linear_model import LogisticRegression

In [34]:
lr = LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression()

In [35]:
y_pred1 = lr.predict(X_test)
accuracy_score(y_test, y_pred1)

0.9807669263031755

In [36]:
print(classification_report(y_test, y_pred1))

              precision    recall  f1-score   support

           0       0.99      0.97      0.98      7907
           1       0.98      0.99      0.98      8783

    accuracy                           0.98     16690
   macro avg       0.98      0.98      0.98     16690
weighted avg       0.98      0.98      0.98     16690

# Creating the Piepline

## Import required libraries

In [37]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

## Encoding

In [39]:
le = LabelEncoder()
y = le.fit_transform(df['label'])
X = df['input']

## Splitting Data

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5, stratify=y)

## Pipeline

In [41]:
spam_pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(lowercase=True, stop_words='english', max_features=5000, ngram_range=(1, 2))),
    ('classifier', LogisticRegression(max_iter=1000, class_weight='balanced'))
])

## Training

In [42]:
spam_pipeline.fit(X_train, y_train)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(max_features=5000, ngram_range=(1, 2),
                                 stop_words='english')),
                ('classifier',
                 LogisticRegression(class_weight='balanced', max_iter=1000))])

## Predicting and Evaluating

In [43]:
y_pred = spam_pipeline.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.9808268424206111
              precision    recall  f1-score   support

           0       0.98      0.97      0.98      7908
           1       0.98      0.99      0.98      8782

    accuracy                           0.98     16690
   macro avg       0.98      0.98      0.98     16690
weighted avg       0.98      0.98      0.98     16690

## Exporting Models

In [44]:
import joblib

joblib.dump(spam_pipeline, 'spam_classifier_pipeline.pkl')
joblib.dump(le, 'label_encoder.pkl')

['label_encoder.pkl']