In [29]:
import pandas as pd
import numpy as np

# Data Fetching

In [30]:
df = pd.read_csv('Housing.csv')

In [31]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

#Exploring the Data

In [32]:
df.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [33]:
df['mainroad'].value_counts()

mainroad
yes    468
no      77
Name: count, dtype: int64

In [34]:
df['furnishingstatus'].value_counts()

furnishingstatus
semi-furnished    227
unfurnished       178
furnished         140
Name: count, dtype: int64

#Splitting the data

In [35]:
X = df.drop('price', axis=1)
y = df['price']

In [36]:
X.shape

(545, 12)

In [37]:
X.head()

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [38]:
df.shape

(545, 13)

# Splitting the data further for training

In [39]:
from sklearn.model_selection import train_test_split

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)

#Import models

In [41]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [61]:
dt = DecisionTreeRegressor()
rg = RandomForestRegressor(n_estimators=500)

# Performing Encoding on categorical and numerical data with different method

In [62]:
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

numeric_features = [0,1,2,3,9]
ohe_features = [4,5,6,7,8,10]
ordinal_features = [11]

preprocess = ColumnTransformer(transformers = [
    ('num', StandardScaler(), numeric_features),
    ('ohe', OneHotEncoder(drop='first'), ohe_features),
    ('ord', OrdinalEncoder(categories=[['furnished','semi-furnished','unfurnished']]), ordinal_features),
])

# Creating Pipeline

In [63]:
pipe1 = Pipeline(steps=[
    ('preprocess', preprocess),
    ('model', dt)
])

pipe2 = Pipeline(steps=[
    ('preprocess', preprocess),
    ('model', rg)
])

#Training the model

In [64]:
pipe1.fit(X_train, y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  [0, 1, 2, 3, 9]),
                                                 ('ohe',
                                                  OneHotEncoder(drop='first'),
                                                  [4, 5, 6, 7, 8, 10]),
                                                 ('ord',
                                                  OrdinalEncoder(categories=[['furnished',
                                                                              'semi-furnished',
                                                                              'unfurnished']]),
                                                  [11])])),
                ('model', DecisionTreeRegressor())])

In [65]:
pipe2.fit(X_train, y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  [0, 1, 2, 3, 9]),
                                                 ('ohe',
                                                  OneHotEncoder(drop='first'),
                                                  [4, 5, 6, 7, 8, 10]),
                                                 ('ord',
                                                  OrdinalEncoder(categories=[['furnished',
                                                                              'semi-furnished',
                                                                              'unfurnished']]),
                                                  [11])])),
                ('model', RandomForestRegressor(n_estimators=500))])

In [66]:
y_pred1 = pipe1.predict(X_test)
y_pred2 = pipe2.predict(X_test)

In [67]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

#Evaluating the model performance

In [68]:
print('Decision Tree Evaluation :')
print('R2 Score: ', r2_score(y_test, y_pred1))
print('MSE: ', mean_squared_error(y_test, y_pred1))
print('MAE :', mean_absolute_error(y_test, y_pred1))

Decision Tree Evaluation :
R2 Score:  0.1316375422238747
MSE:  1954038745412.844
MAE : 1038857.7981651376

In [69]:
print('Random Forest Evaluation :')
print('R2 Score: ', r2_score(y_test, y_pred2))
print('MSE: ', mean_squared_error(y_test, y_pred2))
print('MAE :', mean_absolute_error(y_test, y_pred2))

Random Forest Evaluation :
R2 Score:  0.5879552631982127
MSE:  927206575254.4407
MAE : 725171.5497247707

In [70]:
from sklearn.linear_model import LinearRegression

#Baseline Model testing

In [71]:
lr = LinearRegression()

pipe3 = Pipeline(steps=[
    ('preprocess', preprocess),
    ('model', lr)
])

pipe3.fit(X_train, y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  [0, 1, 2, 3, 9]),
                                                 ('ohe',
                                                  OneHotEncoder(drop='first'),
                                                  [4, 5, 6, 7, 8, 10]),
                                                 ('ord',
                                                  OrdinalEncoder(categories=[['furnished',
                                                                              'semi-furnished',
                                                                              'unfurnished']]),
                                                  [11])])),
                ('model', LinearRegression())])

In [73]:
y_pred3 = pipe3.predict(X_test)

In [74]:
print('Linear Regression Evaluation :')
print('R2 Score: ', r2_score(y_test, y_pred2))
print('MSE: ', mean_squared_error(y_test, y_pred2))
print('MAE :', mean_absolute_error(y_test, y_pred2))

Linear Regression Evaluation :
R2 Score:  0.5879552631982127
MSE:  927206575254.4407
MAE : 725171.5497247707

#Improving the metrics/performance of the models

In [75]:
y_log = np.log1p(y_train)
y_log_test = np.log1p(y_test)

##Training models again after tranformation

In [76]:
pipe1.fit(X_train, y_log)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  [0, 1, 2, 3, 9]),
                                                 ('ohe',
                                                  OneHotEncoder(drop='first'),
                                                  [4, 5, 6, 7, 8, 10]),
                                                 ('ord',
                                                  OrdinalEncoder(categories=[['furnished',
                                                                              'semi-furnished',
                                                                              'unfurnished']]),
                                                  [11])])),
                ('model', DecisionTreeRegressor())])

In [77]:
pipe2.fit(X_train, y_log)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  [0, 1, 2, 3, 9]),
                                                 ('ohe',
                                                  OneHotEncoder(drop='first'),
                                                  [4, 5, 6, 7, 8, 10]),
                                                 ('ord',
                                                  OrdinalEncoder(categories=[['furnished',
                                                                              'semi-furnished',
                                                                              'unfurnished']]),
                                                  [11])])),
                ('model', RandomForestRegressor(n_estimators=500))])

In [78]:
pipe3.fit(X_train, y_log)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  [0, 1, 2, 3, 9]),
                                                 ('ohe',
                                                  OneHotEncoder(drop='first'),
                                                  [4, 5, 6, 7, 8, 10]),
                                                 ('ord',
                                                  OrdinalEncoder(categories=[['furnished',
                                                                              'semi-furnished',
                                                                              'unfurnished']]),
                                                  [11])])),
                ('model', LinearRegression())])

In [79]:
y_prob1 = pipe1.predict(X_test)
y_prob2 = pipe2.predict(X_test)
y_prob3 = pipe3.predict(X_test)

# Evaluation after Y transformation using y np.log1p(y)

In [82]:
print('Decision Tree Evaluation :')
print('R2 Score: ', r2_score(y_log_test, y_prob1))
print('MSE: ', mean_squared_error(y_log_test, y_prob1))
print('MAE :', mean_absolute_error(y_log_test, y_prob1))
print("\n")

print('Random Forest Evaluation :')
print('R2 Score: ', r2_score(y_log_test, y_prob2))
print('MSE: ', mean_squared_error(y_log_test, y_prob2))
print('MAE :', mean_absolute_error(y_log_test, y_prob2))
print("\n")

print('Linear Regression Evaluation :')
print('R2 Score: ', r2_score(y_log_test, y_prob2))
print('MSE: ', mean_squared_error(y_log_test, y_prob2))
print('MAE :', mean_absolute_error(y_log_test, y_prob2))

Decision Tree Evaluation :
R2 Score:  0.0905521633169798
MSE:  0.10357079467977662
MAE : 0.24369120560354376


Random Forest Evaluation :
R2 Score:  0.5363325969677826
MSE:  0.05280390964951274
MAE : 0.1750988239602136


Linear Regression Evaluation :
R2 Score:  0.5363325969677826
MSE:  0.05280390964951274
MAE : 0.1750988239602136

# Performance is Increased